[legends]
SK_A = A
SK_B = B
SK_C = C
SK_D = D
SK_E = E
SK_F = F
SK_G = G
SK_H = H
SK_I = I
SK_J = J
SK_K = K
SK_L = L
SK_M = M
SK_N = N
SK_O = O
SK_P = P
SK_Q = Q
SK_R = R
SK_S = S
SK_T = T
SK_U = U
SK_V = V
SK_W = W
SK_X = X
SK_Y = Y
SK_Z = Z

SK_0 = 0
SK_1 = 1
SK_2 = 2
SK_3 = 3
SK_4 = 4
SK_5 = 5
SK_6 = 6
SK_7 = 7
SK_8 = 8
SK_9 = 9

U_EXLM = !
KC_EXLM = !
U_QUES = ? !
KC_QUES = ? !
KC_GT = >
KC_LT = <
KC_HASH = #
KC_PERC = %
KC_AT = @
KC_DLR = $
KC_CIRC = ^
KC_LCBR = {
KC_LPRN = (
KC_LBRC = [
KC_RCBR = }
KC_RPRN = )
KC_RBRC = ]
KC_PIPE = |
KC_GRV = `
KC_TILD = ~
KC_PLUS = +
KC_AMPR = &
KC_UNDS = _
KC_MINS = - _
KC_EQL = =
U_SL = / \
KC_SLSH = / ?
U_COMM = , <
KC_COMM = , <
KC_DOT = . >
KC_ASTR = *
KC_BSLS = \ |
KC_BSLASH = \ |
U_QUOT = ' "
KC_QUOT = ' "
KC_SCLN = ;
KC_CLN = :
KC_PSCR = PrintSc
KC_NLCK = NumLock
KC_SLCK = ScrLock
KC_INS = Ins
_ =
__ =

SK_EXLM = !
SK_QUES = ? !
SK_GT = >
SK_LT = <
SK_HASH = #
SK_PERC = %
SK_AT = @
SK_DLR = $
SK_CIRC = ^
SK_LCBR = {
SK_LPRN = (
SK_LBRC = [
SK_RCBR = }
SK_RPRN = )
SK_RBRC = ]
SK_PIPE = |
SK_GRV = `
SK_TILD = ~
SK_PLUS = +
SK_AMPR = &
SK_UNDS = _
SK_MINS = - _
SK_EQL = =
SK_SLSH = / ?
SK_COMM = , <
SK_DOT = . >
SK_ASTR = *
SK_BSLS = \ |
SK_BSLASH = \ |
SK_QUOT = ' "
SK_SCLN = : ;
SK_COLN = :

KC_MS_U = MOUSE ↑
KC_MS_D = MOUSE ↓
KC_MS_L = MOUSE ←
KC_MS_R = MOUSE →
KC_WH_U = WHEEL ↑
KC_WH_D = WHEEL ↓
KC_WBAK = ⯬
KC_WFWD = ⯮

C(KC_A) = Ctrl+A
C(KC_B) = Ctrl+B
C(KC_C) = Ctrl+C
C(KC_D) = Ctrl+D
C(KC_E) = Ctrl+E
C(KC_F) = Ctrl+F
C(KC_G) = Ctrl+G
C(KC_H) = Ctrl+H
C(KC_I) = Ctrl+I
C(KC_J) = Ctrl+J
C(KC_K) = Ctrl+K
C(KC_L) = Ctrl+L
C(KC_M) = Ctrl+M
C(KC_N) = Ctrl+N
C(KC_O) = Ctrl+O
C(KC_P) = Ctrl+P
C(KC_Q) = Ctrl+Q
C(KC_R) = Ctrl+R
C(KC_S) = Ctrl+S
C(KC_T) = Ctrl+T
C(KC_U) = Ctrl+U
C(KC_V) = Ctrl+V
C(KC_W) = Ctrl+W
C(KC_X) = Ctrl+X
C(KC_Y) = Ctrl+Y
C(KC_Z) = Ctrl+Z

C(SK_A) = Ctrl+A
C(SK_B) = Ctrl+B
C(SK_C) = Ctrl+C
C(SK_D) = Ctrl+D
C(SK_E) = Ctrl+E
C(SK_F) = Ctrl+F
C(SK_G) = Ctrl+G
C(SK_H) = Ctrl+H
C(SK_I) = Ctrl+I
C(SK_J) = Ctrl+J
C(SK_K) = Ctrl+K
C(SK_L) = Ctrl+L
C(SK_M) = Ctrl+M
C(SK_N) = Ctrl+N
C(SK_O) = Ctrl+O
C(SK_P) = Ctrl+P
C(SK_Q) = Ctrl+Q
C(SK_R) = Ctrl+R
C(SK_S) = Ctrl+S
C(SK_T) = Ctrl+T
C(SK_U) = Ctrl+U
C(SK_V) = Ctrl+V
C(SK_W) = Ctrl+W
C(SK_X) = Ctrl+X
C(SK_Y) = Ctrl+Y
C(SK_Z) = Ctrl+Z

KC_LGUI = LGUI ◆
KC_RGUI = RGUI ◆
KC_LALT = LALT ⎇
KC_RALT = AltGr
KC_LSFT = LSFT ⇧
KC_RSFT = RSFT ⇧
KC_LCTL = LCTL ⎈
KC_RCTL = RCTL ⎈

CTL_ESC = ESC/⎈
CTL_QUOT= ' "/⎈
ALT_ENT = ⏎ /⎇
KC_APP = MENU

NAV_TAB = TAB/NAV
MS_CAPS = CAPS/MS
SYM_ENT = ⏎/SYM
NAV_UND = _/NAV

OS_LSFT = 1-SHOT⇧
OS_RSFT = 1-SHOT⇧

A_ACUTE = Á
AE_ACUTE = Ǽ
C_ACUTE = Ć
E_ACUTE = É
G_ACUTE = Ǵ
I_ACUTE = Í
K_ACUTE = Ḱ
L_ACUTE = Ĺ
M_ACUTE = Ḿ
N_ACUTE = Ń
O_ACUTE = Ó
OBAR_ACUTE = Ǿ
P_ACUTE = Ṕ
R_ACUTE = Ŕ
S_ACUTE = Ś
U_ACUTE = Ú
W_ACUTE = Ẃ
Y_ACUTE = Ý
Z_ACUTE = Ź

A_CARON = Ǎ
C_CARON = Č
D_CARON = Ď
E_CARON = Ě
G_CARON = Ǧ
H_CARON = Ȟ
I_CARON = Ǐ
j_CARON = ǰ
K_CARON = Ǩ
L_CARON = Ľ
N_CARON = Ň
O_CARON = Ǒ
R_CARON = Ř
S_CARON = Š
T_CARON = Ť
U_CARON = Ǔ
Z_CARON = Ž

A_CIRC = Â
C_CIRC = Ĉ
E_CIRC = Ê
G_CIRC = Ĝ
H_CIRC = Ĥ
I_CIRC = Î
J_CIRC = Ĵ
O_CIRC = Ô
S_CIRC = Ŝ
U_CIRC = Û
W_CIRC = Ŵ
Y_CIRC = Ŷ
Z_CIRC = Ẑ

A_DIA = Ä
E_DIA = Ë
H_DIA = Ḧ
I_DIA = Ï
O_DIA = Ö
t_DIA = ẗ
U_DIA = Ü
W_DIA = Ẅ
X_DIA = Ẍ
Y_DIA = Ÿ

NK_ON = NKROon
NK_OFF = NKROoff

STN_N1 = #1
STN_N2 = #2
STN_N3 = #3
STN_N4 = #4
STN_N5 = #5
STN_N6 = #6
STN_N7 = #7
STN_N8 = #8
STN_N9 = #9
STN_NA = NA
STN_S1 = S1
STN_TL = T-
STN_PL = P-
STN_HL = H-
STN_ST1 = *1
STN_ST3 = *3
STN_FR = -F
STN_PR = -P
STN_LR = -L
STN_TR = -T
STN_DR = -D
STN_S2 = S2
STN_KL = K-
STN_WL = W-
STN_RL = R- 
STN_ST2 = *2
STN_ST4 = *4
STN_RR = -R
STN_BR = -B
STN_GR = -G
STN_SR = -S
STN_ZR = -Z
STN_A = A-
STN_O = O-
STN_E = -E
STN_U = -U

SH_OS = SWAPHNDS
